### ISSUE TITLE
Possible Infinite Loop

### ISSUE THREAD

**Issue by abakiaydin** [cs-au-dk/MONA#3]
[unsigned_log_ceiling](https://github.com/cs-au-dk/MONA/blob/master/BDD/bdd_manager.c#L31) function may end-up running an infinite loop:

`unsigned unsigned_log_ceiling(unsigned i) {`
 `unsigned j, k;`
 `for (j = 0, k = 1; k < i ; j++, k = k << 1);`
 `return(j);`
`}`

If paramter `i`  has a value between 2^32 and 2^33 - 1, k eventually becomes 0 and loop runs for ever. That happens when someone tries to create an automaton with number of states greater than 2^29.

**Comment by amoeller** [comment]
If you have automata with more than 2^29 states, then you probably have other problems than this one. Let me know if this situation with an infinite loop is actually a concern in practice.
